prompt_for_chatgpt = """You are a clinical decision support assistant.
Your role is not to recite guidelines verbatim but to produce a short, clinically actionable synthesis that combines:
Guideline recommendations (NCCN, ASCO, ESMO, USPSTF, etc.)
High-grade evidence (meta-analyses, landmark RCTs)
Patient-specific factors (age, comorbidities, renal function, biomarkers, stage)
Risk stratification (high-risk features vs low-risk)
Treatment ranking (preferred → alternatives)
Monitoring and surveillance recommendations
Contraindications and toxicity considerations
Your answers must be:
Short (7-10 sentences max)
Clinically actionable
Personalized
Multi-guideline synthesized
Evidence-weighted (guidelines > meta-analyses > RCTs > observational)
Explicit about what NOT to do
Highly structured
Cited using retrieved PubMed IDs or guideline names
Do NOT quote NCCN or other proprietary guidelines verbatim.
Instead, summarize the recommendation in your own words using retrieved guidance.
Avoid long paragraphs.
Aim for concise, expert-level answers that a busy attending would appreciate."""  

system_prompt_for_compare = """Leny is an CDSS based on the evidences. beating OpenEvidence is our project's goal.
 so i have to compare the answers provide by my RAG and answer from OpenEvidence."""
prompt_for_compare = """I will give you test question, answer of leny and answer of OpenEvidence and prompt that processes the RAG results to generates a human-readable message in Leny.
 So you must provide me comparison results with below requirements. 
   1. Score the quality of answer from Leny and answer from OpenEvidence respectively in scale of 1 to 10.
   2. Provide me detail comparison results between answer from Leny and answer from OpenEvidence in the following aspects:
   3. clinical relevance, accuracy, completeness, clarity, conciseness, and usefulness for clinical decision-making.
   4. Highlight specific strengths and weaknesses of each answer.
   5. Suggest concrete improvements for Leny's answer to better meet clinicians' needs.
   6. Based on your comparison, provide me updated prompt that can help Leny to improve its answer quality.
   7. Your updated prompt should be strongly, professionaly and clearly written.
   8. Your updated prompt should be able to guide Leny to generate high-quality answers that effectively support clinical decision-making.
   9. Your updated prompt should address the weaknesses identified in Leny's answer and leverage its strengths.
   10. Your updated prompt should be concise yet comprehensive, ensuring clarity and ease of understanding.
 """

questions = [
  "What is the evidence-based first-line approach for chronic low back pain?",
  "How effective are ACE inhibitors compared with ARBs for hypertension control?",
  "What are the recommended diagnostic steps for persistent fatigue in adults?",
  "How does metformin compare with lifestyle changes for prediabetes?",
  "What are the indications for starting statins in primary prevention?",
  "What monitoring is recommended for long-term NSAID use?",
  "How accurate is A1C for diagnosing diabetes compared with fasting glucose?",
  "What lifestyle interventions help reduce systolic blood pressure?",
  "What is the role of coronary artery calcium scoring in risk assessment?",
  "What factors help distinguish viral from bacterial sinusitis?","What is the comparative effectiveness of different antihistamines for allergic rhinitis?",
  "How useful is CRP testing for general infection workup?",
  "What evidence supports intermittent fasting for metabolic improvement?",
  "How effective is vitamin D supplementation for fatigue?",
  "What are the risks and benefits of long-term PPI use?",
  "What criteria indicate the need for imaging in acute headache?",
  "What is the recommended evaluation for chronic cough?",
  "What evidence exists for probiotics in digestive health?",
  "How does aerobic exercise compare to strength training for weight management?",
  "What are validated screening tools for depression in primary care?",
  "What factors predict progression from prehypertension to hypertension?",
  "How accurate are home blood pressure monitors?",
  "Which lifestyle changes reduce LDL cholesterol the most?",
  "What is the evidence for magnesium supplementation in migraine prevention?",
  "What medications can elevate liver enzymes?",
  "What are the most reliable methods to distinguish viral vs bacterial pharyngitis?",
  "How does PCR compare to antigen testing for respiratory infections?",
  "What is the recommended evaluation for persistent fever without source?",
  "What evidence supports antiviral use in influenza?",
  "How accurate is rapid strep testing in adults?",
  "What factors predict severe outcomes in pneumonia?",
  "What is the recommended follow-up for recurrent urinary tract symptoms?",
  "How does doxycycline compare to azithromycin for atypical infections?",
  "What screening is recommended after exposure to a bloodborne pathogen?",
  "What is the clinical value of procalcitonin in infection evaluation?",
  "What lifestyle factors reduce recurrent UTIs?",
  "How effective are vaccines in preventing shingles in older adults?",
  "What is the diagnostic accuracy of chest X-ray for pneumonia?",
  "What labs help differentiate viral from bacterial gastroenteritis?",
  "What evidence exists for zinc in shortening cold duration?",
  "What is the best approach to evaluating travelers with fever?",
  "What symptoms predict complications in sinus infections?",
  "How effective is hand hygiene in reducing respiratory infections?",
  "What are the common causes of persistent lymphadenopathy?",
  "What factors increase the risk of recurrent skin infections?",
  "How do macrolides compare to fluoroquinolones in respiratory infections?",
  "What is the evidence for IV vs oral antibiotics in moderate infections?",
  "How reliable are home COVID tests in early infection?",
  "What screenings are recommended for sexually transmitted infections?",
  "What findings help differentiate cellulitis from dermatitis?",
  "What evidence supports early intervention in stage 1 hypertension?",
  "When should ambulatory blood pressure monitoring be used?",
  "What is the role of aspirin in primary cardiovascular prevention?",
  "What tests are recommended for palpitations?",
  "What lifestyle changes reduce arrhythmia risk?",
  "What is the accuracy of stress testing for coronary artery disease?",
  "When is echocardiography indicated for dyspnea?",
  "How effective are beta blockers for heart rate control?",
  "What factors predict progression of valvular disease?",
  "How does LDL lowering correlate with cardiovascular risk reduction?",
  "What is the evidence for omega-3 supplements in heart health?",
  "What lab markers indicate cardiac strain?",
  "What findings help identify heart failure?",
  "What exercise regimens benefit patients with stable heart disease?",
  "How reliable are home ECG devices?",
  "What are the recommended follow-ups after an abnormal stress test?",
  "How does family history affect cardiovascular risk assessment?",
  "What are common causes of secondary hypertension?",
  "What factors guide the use of coronary CT angiography?",
  "What symptoms suggest arrhythmias requiring evaluation?",
  "What evidence supports salt reduction for blood pressure control?",
  "What are the risks of long-term stimulant use on heart rhythm?",
  "What is the value of NT-proBNP testing?",
  "What distinguishes cardiac from non-cardiac chest pain?",
  "How effective is cardiac rehabilitation after heart events?",
  "What criteria guide imaging for persistent cough?",
  "What evidence supports inhaled corticosteroids in asthma control?",
  "What findings differentiate asthma from COPD?",
  "What tests evaluate unexplained shortness of breath?",
  "How accurate is spirometry in diagnosing airway disease?",
  "What environmental factors worsen asthma symptoms?",
  "What is the recommended assessment for chronic wheezing?",
  "What lifestyle changes improve COPD outcomes?",
  "What findings predict severe asthma attacks?",
  "What evidence supports pulmonary rehabilitation?",
  "What are common causes of nighttime cough?",
  "How effective are air purifiers for respiratory symptoms?",
  "What findings suggest restrictive lung disease?",
  "What tests evaluate suspected sleep apnea?",
  "How does cold weather affect respiratory function?",
  "What factors increase pneumonia risk?",
  "What is the evidence for early mobilization in respiratory illness recovery?",
  "What symptoms suggest pulmonary embolism?",
  "What labs help evaluate unexplained hypoxia?",
  "What predicts need for hospitalization in respiratory infections?",
  "What is the role of CT imaging in chronic lung disease?",
  "What evidence supports breathing exercises in asthma?",
  "What triggers contribute to exercise-induced bronchospasm?",
  "What clinical signs differentiate upper vs lower respiratory symptoms?",
  "What is the usefulness of FeNO testing?",
  "What findings help distinguish migraine from tension headache?",
  "What tests evaluate chronic dizziness?",
  "How effective is magnesium for migraine prevention?",
  "What features suggest neuropathic pain?",
  "What is the recommended evaluation for new-onset headaches?",
  "How to evaluate sudden episodes of faintness?",
  "What are validated tools for cognitive assessment?",
  "What findings suggest seizure disorder?",
  "What tests evaluate chronic numbness?",
  "What lifestyle changes help reduce migraine frequency?",
  "What neurologic signs require urgent evaluation?",
  "What are causes of sudden muscle weakness?",
  "What distinguishes peripheral from central vertigo?",
  "What labs evaluate neuropathy causes?",
  "What factors increase risk of recurrent migraines?",
  "What evidence supports riboflavin in migraines?",
  "What are early signs of neurodegenerative diseases?",
  "What findings suggest carpal tunnel syndrome?",
  "What tests evaluate chronic tingling?",
  "What are causes of tremors in adults?",
  "What symptoms suggest autonomic dysfunction?",
  "What helps differentiate stroke mimics from stroke signs?",
  "What imaging is recommended for chronic headaches?",
  "What improves sleep quality for people with tension headaches?",
  "What clinical signs indicate possible nerve compression?",
  "What labs evaluate unexplained weight changes?",
  "What is the most evidence-based diet for glucose control?",
  "What findings suggest thyroid dysfunction?",
  "What labs evaluate hair thinning?",
  "What screening is recommended for metabolic syndrome?",
  "How does intermittent fasting compare to calorie reduction?",
  "What factors increase risk of insulin resistance?",
  "What evidence supports cinnamon for glucose regulation?",
  "What findings distinguish hypo from hyperthyroidism?",
  "What tests evaluate cortisol abnormalities?",
  "What lifestyle choices improve insulin sensitivity?",
  "What causes abnormal menstrual cycles in endocrine disorders?",
  "What labs evaluate low energy levels?",
  "How does sleep duration affect hormone balance?",
  "What dietary factors influence LDL cholesterol?",
  "What symptoms suggest adrenal disorders?",
  "What tests evaluate elevated prolactin?",
  "What evidence links gut health to hormone regulation?",
  "What findings differentiate PCOS from similar conditions?",
  "What factors increase risk of osteoporosis?",
  "What labs assess vitamin deficiencies?",
  "What diet supports healthy thyroid function?",
  "What markers predict prediabetes progression?",
  "What interventions help with metabolic inflammation?",
  "What lifestyle habits affect blood sugar variability?",
  "What labs evaluate chronic abdominal discomfort?",
  "What evidence supports probiotics in digestive health?",
  "What findings differentiate IBS from IBD?",
  "What tests evaluate chronic bloating?",
  "What lifestyle changes reduce acid reflux symptoms?",
  "What are causes of persistent nausea?",
  "What labs evaluate liver inflammation?",
  "What findings suggest gallbladder disease?",
  "What tests evaluate unexplained diarrhea?",
  "What symptoms indicate malabsorption?",
  "What is the evidence for low-FODMAP diets?",
  "What findings suggest peptic ulcer disease?",
  "What tests evaluate chronic constipation?",
  "What supplements affect digestive motility?",
  "What are causes of elevated liver enzymes?",
  "What symptoms suggest celiac disease?",
  "How effective is fiber for digestive regularity?",
  "What findings indicate pancreatic issues?",
  "What labs evaluate bile duct problems?",
  "What imaging is needed for persistent abdominal pain?",
  "What diet modifications help with gastritis symptoms?",
  "What findings differentiate functional from inflammatory GI disorders?",
  "What evidence supports herbal supplements for digestion?",
  "What symptoms suggest lactose intolerance?",
  "What are common triggers for GERD?",
  "What findings differentiate joint inflammation from mechanical pain?",
  "What evidence supports exercise therapy for knee pain?",
  "What tests evaluate chronic muscle stiffness?",
  "What lifestyle changes help with chronic joint discomfort?",
  "What findings suggest tendon problems?",
  "What labs evaluate muscle inflammation?",
  "What is the evidence for heat therapy in muscle recovery?",
  "What factors increase risk of recurrent sprains?",
  "What symptoms suggest rotator cuff involvement?",
  "How effective is stretching for back discomfort?",
  "What findings differentiate arthritis types?",
  "What tests evaluate chronic shoulder pain?",
  "What evidence supports yoga for musculoskeletal health?",
  "What symptoms suggest nerve-related back pain?",
  "What labs screen for autoimmune joint disorders?",
  "What findings indicate bursitis?",
  "What role does ergonomics play in neck discomfort?",
  "How effective are braces for joint support?",
  "What symptoms suggest hip joint pathology?",
  "What findings help distinguish muscle strain from ligament injury?",
  "What therapies help with chronic neck tension?",
  "What evidence supports physical therapy for chronic pain?",
  "What tests evaluate persistent limb swelling?",
  "What symptoms predict recovery time for soft tissue injuries?",
  "What findings suggest mechanical vs inflammatory pain patterns?"
]
